<?php

$phoneticAlphabet = array('Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot', 'Golf', 'Hotel', 'India', 'Juliet', 'Kilo', 'Lima', 'Mike', 'November', 'Oscar', 'Papa', 'Quebec', 'Romeo', 'Sierra', 'Tango', 'Uniform', 'Victor', 'Whiskey', 'X-ray', 'Yankee', 'Zulu');

$greekAlphabet = array('Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', 'Zeta', 'Eta', 'Theta', 'Iota', 'Kappa', 'Lambda', 'Mu', 'Nu', 'Xi', 'Omicron', 'Pi', 'Rho', 'Sigma', 'Tau', 'Upsilon', 'Phi', 'Chi', 'Psi', 'Omega');

$romanNumerals = array('I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII', 'XIII', 'XIV', 'XV', 'XVI', 'XVII', 'XVIII', 'XIX', 'XX');

$stationNames = array('Array','Base','Bomb','Center','Checkpoint','City','Colony','Complex','Construct','Crypt','Death-trap','Depot','Drydock','Edition','Facility','Factory','Fishery','Fortification','Fortress','Fortress','Frontier','Hangar','Hazard','Hive','HQ','Hub','Hut','Installation','Lab','Monitor','Monkey','No-Moon','Object','Observatory','Office','Outpost','Planet-Cracker','Platform','Port','Prison','Relay','Roost','Space-hulk','Station','Stopover','Suffix','Tomb','Town','Trade Post','Village','Waypoint','Waystation');

$stationAdjectives = array('Imperium', 'Heretical', 'Psychic', 'Elegant', 'Common', 'Uncommon', 'Rare', 'Unique', 'Houseruled', 'Religious', 'Atheist', 'Traditional', 'Mad', 'Super', 'Ultra', 'Secret', 'Top Secret', 'Deep', 'Death', 'Central', 'Main', 'Government', 'Automated', 'Experimental', 'Augmented');

$systPrefixes = array (
  "NGC", //New General Catalouge 
  "BNR", //Bluespace Navigation Relay
  "LNW", //Local Navigation Waypoint
);

$systNames = array(
  "Ducatel", //Fictional sugar company from Left 4 Dead 2
  "Huston",
  "Astriala",
  "Lattice",
  "Axios", //Roman general (also used in Halo 4: Forward Unto Dawn)
  "Trosper", //GUESS WHO
  "Blivet",
  "Blivert",
  "Omicron Persei VIII", //Futurama (of course)
  "Welch", //People in the games industry that have been influential
  "Burch",
  "Williams",
  "Smart",
  "Hector",
  "Newell",
  "Wolpaw",
  "Laidlaw",
  "Faliszek",
  "Morasky",
  "Coulton",
  "Bailey",
  "McLain",
  "Newman",
  "Morris",
  "Delay",
  "Lynn",
  "Dryden",
  "Vaughan",
  "Noonan",
  "Sentos", //Mangled linux distros. Don't judge.
  "Rudhet",
  "Ubuntos",
  "Dibean",
  "Sose",
  "Feedora",
  "Gintoo",
  "Mendreva",
  "Kneppix",
  "Raven", //Paradoxes
  "Berry",
  "Epimenides",
  "Grelling–Nelson",
  "Quine",
  "Yablo",
  "Petronius",
  "Theseus",
  "Benford",
  "Berkson",
  "Simpson",
  "Bertrand",
  "Borel",
  "Grice",
  "Proebsting",
  "Burali-Forti",
  "Cantor",
  "Galileo",
  "Hilbert",
  "Skolem",
  "Benardete",
  "Thomson",
  "Banach–Tarski",
  "Gabriel",
  "Hausdorff",
  "Nikodym",
  "Smale",
  "Abilene",
  "Buridan",
  "Fenno",
  "Kavka",
  "Morton",
  "Newcomb",
  "Parrondo",
  "Archer",
  "Carroll",
  "Archimedes",
  "Aristotle",
  "D'Alembert",
  "Feynman",
  "Fermi",
  "Olbers",
  "Aharonov–Bohm",
  "Einstein–Podolsky–Rosen",
  "Hardy",
  "Klein",
  "Schrödinger",
  "Ehrenfest",
  "Mocanu",
  "Trouton-Noble",
  "Supplee",
  "Gibbs",
  "Loschmidt",
  "Maxwell",
  "Mpemba",
  "Cole",
  "Gray",
  "Lombard",
  "Peto",
  "Pulsus",
  "Sherman",
  "Levinthal",
  "Polchinski",
  "Moravec",
  "Buridan",
  "Fitch",
  "Goodman",
  "Hutton",
  "Meno",
  "Moore",
  "Zeno",
  "Allais",
  "Bertrand",
  "Braess",
  "Deaton",
  "Downs–Thomson",
  "Easterlin",
  "Edgeworth",
  "Ellsberg",
  "Gibson",
  "Giffen",
  "Icarus",
  "Jevon",
  "Leontief",
  "Lucas",
  "Mandeville",
  "Metzler",
  "Scitovsky",
  "Tullock",
  "Tritone",
  "Hegel",
  "Stapp",
  "Stopdale",
  "Bonini", //Last of the paradoxes
  "Lonsdale", //Allotropes of elements, may be adapated
  "Carbyne",
  "Fullerenes",
  "Diphosphor",
  "Ferrite",
  "Promethian",//Last allotropes
  "Aktinos", //Element name etymologies (Mostly greek roots)
  "Arsenikon",
  "Astatos",
  "Barys",
  "Beryl",
  "Wismuth",
  "Bromos",
  "Kadmia",
  "Calx",
  "Chloros",
  "Kobold",
  "Cuprum",
  "Aurum",
  "Ferrum",
  "Neos",
  "Rhodon",
  "Silex",
  "Seolfor",
  "Sufra",
  "Tantalus",
  "Thallos",
  "Stannum",
  "Vanadis",
  "Zarkun", //Last of element etymologies
  "Rivest", //R
  "Shamir", //S
  "Adleman",//A
  "Addison", //Eponyms from wikipedia
  "Aho",
  "Weinberger",
  "Kernighan",
  "Ames",
  "Lidell",
  "Beaufort",
  "Bohr",
  "Boltzmann",
  "Burnside",
  "Descartes",
  "Cassini",
  "Chandrasekhar",
  "Coriolis",
  "Darwin",
  "Doppler",
  "Dvorak",
  "Dunbar",
  "Epstein",
  "Barr",
  "Erlenmeyer",
  "Euler",
  "Faraday",
  "Fermi",
  "Fibonacci",
  "Fujita",
  "Galileo",
  "Galilei",
  "Gauss",
  "Gibbs",
  "Hadrian",
  "Halley",
  "Hawking",
  "Hobbes",
  "Humboldt",
  "Hudson",
  "Hughes",
  "Jarvik",
  "Jeremiah",
  "Kennedy",
  "Kuiper",
  "Lincoln",
  "Langley",
  "Lorentz",
  "Mandlebrot",
  "Messiner",
  "Miranda",
  "Murdock",
  "Murphy",
  "Nelson",
  "Neumann",
  "Ockham",
  "Amea", //Generic words that also work
  "Midlands",
  "Reserve",

);
